### ISSUE TITLE
About how to get the ground truth GED values.

### ISSUE THREAD

**Issue by jiyangbai** [yunshengb/SimGNN#19]
Hello, 

Can I use the nx.graph_edit_distance() function to get the ground truth ged values for graph pairs?

Thanks!

**Comment by yunshengb** [comment]
Yes if the graphs are small enough. For larger graphs, I doubt that
function might take too long. Thanks!

**Comment by jiyangbai** [comment]
Ok, that's great. From the code of your ground truth computing methods, I notice that there is a file

graph-matching-toolkit/src/algorithms/GraphMatching.java

I am not sure if this one is responsible for the ground truth GED values computing, and currently I cannot compile it successfully when I run the ged() function defined in your code. I am wondering how I can compile it on the linux server. Thanks!

**Comment by yunshengb** [comment]
You can try using Eclipse to compile locally first and then try compiling
on server because Eclipse can provide some help on compilation.

Alternatively, you can try using BSS_GED which is a more recent solver
https://github.com/ZongyueQin/Graph-Hashing/tree/master/model/BSS-GED
