### ISSUE TITLE
about the size of input

### ISSUE THREAD

**Issue by marasilence** [yunshengb/SimGNN#4]
Hello
For the graphs with different size, can the Neural Tensor Network ensure the output with same size?
if my graphs doesn't have any node features, and they have different size, can this model work fine ?

**Comment by yunshengb** [comment]
Yes. The model is invariant to the number of nodes/edges of graphs in the dataset, even when the graphs do not have any node features. In that case, the node feature encoder could be set to ``constant``, meaning every node has the same initial representation.
