### ISSUE TITLE
Which model is SimGNN?

### ISSUE THREAD

**Issue by entslscheia** [yunshengb/SimGNN#9]
Hello,

I saw that 3 different models are implemented in your code, namely, siamese_regression, siamese_ranking, and siamese_calssification. Could you please give me a hint on which of them is the model described as SimGNN in your WSDM paper? Are the other two models also relevant?
Many thanks!

**Comment by psp3dcg** [comment]
Yes，I run the coda and see some results such as beam,hungarian,vj except simgnn, so which model is simgnn? Thanks a lot! @yunshengb

**Comment by yunshengb** [comment]
We name simgnn as Siamese in the code. Sorry about the confusion!

**Comment by psp3dcg** [comment]
> We name simgnn as Siamese in the code. Sorry about the confusion!

OK，thank you！
